SELECT
  T.ORIGINAL_TEXT, T.CREATED_AT, CONCAT('http://twitter.com/', T.USER_NAME, '/status/', T.STATUS_ID) AS URL
FROM
  TWEETS T
WHERE
  T.STRIPPED_TEXT LIKE '%cantsleep%' AND
  LENGTH(T.STRIPPED_SORTED_TEXT) < 30