DELETE FROM ANAGRAM_MATCHES
WHERE
  ID
IN
  (SELECT
     A.ID
   FROM
     ANAGRAM_MATCHES A
     INNER JOIN TWEETS T1 ON A.TWEET1_ID = T1.ID
     INNER JOIN TWEETS T2 ON A.TWEET2_ID = T2.ID
   WHERE
     T1.ORIGINAL_TEXT LIKE 'Get Weather%');

DELETE FROM TWEETS
WHERE
  ID
IN
  (SELECT
     T.ID
   FROM
     TWEETS T
   WHERE
     T.ORIGINAL_TEXT LIKE 'Get Weather%');
