ALTER TABLE PUBLIC.ANAGRAM_MATCHES
ADD HAMMING_DISTANCE_STRIPPED_TEXT integer DEFAULT 0 NOT NULL
AFTER EDIT_DISTANCE_STRIPPED_TEXT;

ALTER TABLE PUBLIC.ANAGRAM_MATCHES
ADD LONGEST_COMMON_SUBSTRING_LENGTH_STRIPPED_TEXT integer DEFAULT 0 NOT NULL
AFTER HAMMING_DISTANCE_STRIPPED_TEXT;

ALTER TABLE PUBLIC.ANAGRAM_MATCHES
ADD WORD_COUNT_DIFFERENCE integer DEFAULT 0 NOT NULL
AFTER LONGEST_COMMON_SUBSTRING_LENGTH_STRIPPED_TEXT;

ALTER TABLE PUBLIC.ANAGRAM_MATCHES
ADD TOTAL_WORDS integer DEFAULT 0 NOT NULL
AFTER WORD_COUNT_DIFFERENCE;

ALTER TABLE PUBLIC.ANAGRAM_MATCHES
ADD LCS_LENGTH_TO_TOTAL_LENGTH_RATIO float DEFAULT 0.0 NOT NULL
AFTER TOTAL_WORDS;

ALTER TABLE PUBLIC.ANAGRAM_MATCHES
ADD EDIT_DISTANCE_TO_LENGTH_RATIO float DEFAULT 0.0 NOT NULL
AFTER INVERSE_LCS_LENGTH_TO_TOTAL_LENGTH_RATIO;

ALTER TABLE PUBLIC.ANAGRAM_MATCHES
ADD DIFFERENT_WORD_COUNT_TO_TOTAL_WORD_COUNT_RATIO float DEFAULT 0.0 NOT NULL
AFTER EDIT_DISTANCE_TO_LENGTH_RATIO;

ALTER TABLE PUBLIC.ANAGRAM_MATCHES
ADD INTERESTING_FACTOR float DEFAULT 0.0 NOT NULL
AFTER DIFFERENT_WORD_COUNT_TO_TOTAL_WORD_COUNT_RATIO;