DELETE FROM ANAGRAM_MATCHES
WHERE
  ID
IN
  (SELECT
     A.ID
   FROM
     ANAGRAM_MATCHES A, TWEETS T1, TWEETS T2
   WHERE
     A.TWEET1_ID = T1.ID AND
     A.TWEET2_ID = T2.ID AND
     T1.ORIGINAL_TEXT LIKE 'Get Weather%');

DELETE FROM TWEETS
WHERE
  ID
IN
  (SELECT
     T.ID
   FROM TWEETS T
   WHERE
     T.ORIGINAL_TEXT LIKE 'Get Weather%');
