DELETE FROM
  ANAGRAM_MATCHES
WHERE
  ID NOT IN (SELECT A.ID
             FROM
               ANAGRAM_MATCHES A, TWEETS T1, TWEETS T2
             WHERE
               A.TWEET1_ID = T1.ID AND
               A.TWEET2_ID = T2.ID AND
               A.DIFFERENT_WORD_COUNT_TO_TOTAL_WORD_COUNT_RATIO > 0 AND
               A.EDIT_DISTANCE_TO_LENGTH_RATIO > 0 AND
               A.INVERSE_LCS_LENGTH_TO_TOTAL_LENGTH_RATIO > 0 AND
               A.IS_SAME_REARRANGED != 1);