SELECT
  A.INTERESTING_FACTOR    AS INTERESTING,
  T1.ORIGINAL_TEXT        AS T1_ORIG,
  T2.ORIGINAL_TEXT        AS T2_ORIG,
  T1.STRIPPED_SORTED_TEXT AS SST
FROM
  ANAGRAM_MATCHES A
  INNER JOIN TWEETS T1 ON A.TWEET1_ID = T1.ID
  INNER JOIN TWEETS T2 ON A.TWEET2_ID = T2.ID
WHERE
  T1.STRIPPED_SORTED_TEXT IN (SELECT T1.STRIPPED_SORTED_TEXT
                              FROM
                                ANAGRAM_MATCHES A
                                INNER JOIN TWEETS T1 ON A.TWEET1_ID = T1.ID
                                INNER JOIN TWEETS T2 ON A.TWEET2_ID = T2.ID
                              GROUP BY
                                T1.STRIPPED_SORTED_TEXT
                              HAVING
                                COUNT(*) > 1 AND
                                AVG(A.INTERESTING_FACTOR) > 0.4)
ORDER BY T1.STRIPPED_SORTED_TEXT DESC;

SELECT
  T1.STRIPPED_SORTED_TEXT,
  COUNT(*) AS CNT,
  MAX(A.INTERESTING_FACTOR) AS MAX_INT
FROM
  ANAGRAM_MATCHES A
  INNER JOIN TWEETS T1 ON A.TWEET1_ID = T1.ID
  INNER JOIN TWEETS T2 ON A.TWEET2_ID = T2.ID
GROUP BY
  T1.STRIPPED_SORTED_TEXT
HAVING
  COUNT(*) > 1 AND
  AVG(A.INTERESTING_FACTOR) > 0.4
ORDER BY
  MAX_INT DESC,
  CNT DESC;