SELECT
  A.EDIT_DISTANCE_ORIGINAL_TEXT AS DIST_ORIG,
  A.EDIT_DISTANCE_STRIPPED_TEXT AS DIST_STRIPPED,
  A.HAMMING_DISTANCE_STRIPPED_TEXT AS HAMMING,
  A.LONGEST_COMMON_SUBSTRING_LENGTH_STRIPPED_TEXT AS LCS,
  A.WORD_COUNT_DIFFERENCE AS WORD_COUNT_DIFF,
  A.TOTAL_WORDS AS TOTAL_WORDS,
  1.0 - (A.LONGEST_COMMON_SUBSTRING_LENGTH_STRIPPED_TEXT * 1.0 / LENGTH(T1.STRIPPED_TEXT)) AS LCS_TO_LENGTH_RATIO,
  A.EDIT_DISTANCE_STRIPPED_TEXT * 1.0 / LENGTH(T1.STRIPPED_TEXT) AS DIST_TO_LENGTH_RATIO,
  A.WORD_COUNT_DIFFERENCE * 1.0 / A.TOTAL_WORDS AS DIFF_WORD_RATIO,
  T1.ORIGINAL_TEXT AS T1_ORIG,
  T2.ORIGINAL_TEXT AS T2_ORIG,
  CONCAT('http://twitter.com/', T1.USER_NAME, '/status/', T1.STATUS_ID) AS TWEET1_URL,
  CONCAT('http://twitter.com/', T2.USER_NAME, '/status/', T2.STATUS_ID) AS TWEET2_URL
FROM
  ANAGRAM_MATCHES A, TWEETS T1, TWEETS T2
WHERE
  A.TWEET1_ID = T1.ID AND
  A.TWEET2_ID = T2.ID AND
  A.EDIT_DISTANCE_STRIPPED_TEXT > 0 AND
  A.LONGEST_COMMON_SUBSTRING_LENGTH_STRIPPED_TEXT <= LENGTH(T1.STRIPPED_TEXT) * 0.50 AND
  A.EDIT_DISTANCE_STRIPPED_TEXT >= LENGTH(T1.STRIPPED_TEXT) * 0.10 AND
  A.EDIT_DISTANCE_ORIGINAL_TEXT > 0 AND
  A.WORD_COUNT_DIFFERENCE > 0
ORDER BY
  LCS, WORD_COUNT_DIFF