SELECT
  A.EDIT_DISTANCE_ORIGINAL_TEXT AS DIST_ORIG,
  A.EDIT_DISTANCE_STRIPPED_TEXT AS DIST_STRIPPED,
  T1.ORIGINAL_TEXT AS T1_ORIG,
  T2.ORIGINAL_TEXT AS T2_ORIG,
  CONCAT('http://twitter.com/', T1.USER_NAME, '/status/', T1.STATUS_ID) AS TWEET1_URL,
  CONCAT('http://twitter.com/', T2.USER_NAME, '/status/', T2.STATUS_ID) AS TWEET2_URL
FROM
  ANAGRAM_MATCHES A, TWEETS T1, TWEETS T2
WHERE
  A.TWEET1_ID = T1.ID AND
  A.TWEET2_ID = T2.ID AND
  (A.EDIT_DISTANCE_STRIPPED_TEXT > 0 OR A.EDIT_DISTANCE_ORIGINAL_TEXT > 0) AND
  T1.ORIGINAL_TEXT NOT LIKE 'Get Weather Updates%'
ORDER BY
  DIST_STRIPPED DESC